Repository adisve/tumble-for-kronox, pull requests merged in 2022-10, with the labels that each got.

#93 Updated logo on search page
  lib/core/ui/search/search/search_page_slideable_logo.dart
  lib/core/ui/search/search/tumble_search_page.dart
Labels: enhancement

#96 User overview/external links
  assets/images/canvas_logo.png
  assets/images/kronox_logo.png
  assets/images/ladok_logo.png
  lib/core/ui/user/overview/user_account_info.dart
  pubspec.yaml
Labels: enhancement

#97 Fix bug where scaffold message shows reverse fail/success messages
  lib/core/ui/schedule/event_options.dart
Labels: bug

#98 Updated logo
  android/app/src/main/play_store_512.png
  android/app/src/main/res/drawable-hdpi/splash.png
  android/app/src/main/res/drawable-hdpi/splash_foreground.png
  android/app/src/main/res/drawable-mdpi/splash.png
  android/app/src/main/res/drawable-mdpi/splash_foreground.png
  android/app/src/main/res/drawable-xhdpi/splash.png
  android/app/src/main/res/drawable-xhdpi/splash_foreground.png
  android/app/src/main/res/drawable-xxhdpi/splash.png
  android/app/src/main/res/drawable-xxhdpi/splash_foreground.png
  android/app/src/main/res/drawable-xxxhdpi/splash.png
  android/app/src/main/res/drawable-xxxhdpi/splash_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  assets/images/ic_launcher.png
  lib/core/ui/login/login_page_root.dart
  lib/core/ui/search/search/search_page_slideable_logo.dart
  pubspec.yaml
Labels: enhancement

#99 Update contributors modal
  lib/core/ui/app_switch/misc/tumble_drawer/contributors_modal/contributors_modal.dart
Labels: enhancement

#108 Added chinese localization
  lib/locale/app_zh.arb
Labels: locale

#112 Fix username clearing on failed login
  lib/core/extensions/response_extensions/user_parser.dart
  lib/core/ui/login/cubit/auth_cubit.dart
  lib/core/ui/login/login_page_root.dart
  lib/locale/app_en.arb
Labels: bug, enhancement

#114 Fix user info overflow
  lib/core/ui/search/search/searchbar_and_logo_container.dart
  lib/core/ui/user/overview/user_account_info.dart
Labels: bug

#115 Update english locale with search page strings
  lib/core/ui/data/groups/search_page.dart
  lib/core/ui/search/search/searchbar_and_logo_container.dart
  lib/core/ui/search/search/tumble_search_page.dart
  lib/locale/app_en.arb
Labels: enhancement, locale

#119 Removed list view animations
  lib/core/ui/app_switch/cubit/app_switch_cubit.dart
  lib/core/ui/schedule/modal_info_row.dart
  lib/core/ui/schedule/tumble_list_view/tumble_list_view.dart
  lib/core/ui/search/cubit/search_page_cubit.dart
  lib/core/ui/search/search/schedule_preview.dart
Labels: bug

#120 List view/year divider
  lib/core/ui/login/login_page_root.dart
  lib/core/ui/schedule/tumble_list_view/tumble_list_view.dart
  lib/core/ui/schedule/tumble_week_view/tumble_week_view.dart
  lib/core/ui/schedule/tumble_week_view/week_list_view.dart
  lib/core/ui/search/search/schedule_preview.dart
Labels: enhancement

#122 UI/list view/lazyload
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile
  ios/Podfile.lock
  lib/core/api/backend/initial/background_task.dart
  lib/core/api/backend/repository/backend_repository.dart
  lib/core/api/backend/repository/cache_repository.dart
  lib/core/api/backend/response_types/schedule_or_programme_response.dart
  lib/core/extensions/response_extensions/schedule_and_programme_parser.dart
  lib/core/navigation/navigation_routes.dart
  lib/core/ui/app_switch/cubit/app_switch_cubit.dart
  lib/core/ui/app_switch/cubit/app_switch_state.dart
  lib/core/ui/app_switch/data/event_types.dart
  lib/core/ui/app_switch/initialized_navigation_root_page.dart
  lib/core/ui/app_switch/misc/tumble_details_modal_base.dart
  lib/core/ui/app_switch/misc/tumble_drag_pill.dart
  lib/core/ui/app_switch/misc/tumble_drawer/cubit/drawer_cubit.dart
  lib/core/ui/app_switch/misc/tumble_drawer/drawer_generic/app_bookmark_schedule_toggle.dart
  lib/core/ui/app_switch/misc/tumble_drawer/drawer_generic/app_language_picker.dart
  lib/core/ui/app_switch/misc/tumble_drawer/drawer_generic/app_notification_time_picker.dart
  lib/core/ui/app_switch/misc/tumble_drawer/drawer_generic/app_theme_picker.dart
  lib/core/ui/app_switch/misc/tumble_drawer/tumble_app_drawer.dart
  lib/core/ui/data/groups/pop_up.dart
  lib/core/ui/permission_handler.dart
  lib/core/ui/schedule/event_modal.dart
  lib/core/ui/schedule/event_options.dart
  lib/core/ui/schedule/tumble_calendar_view/tumble_calendar_view.dart
  lib/core/ui/schedule/tumble_list_view/data/to_top_button.dart
  lib/core/ui/schedule/tumble_list_view/tumble_list_view.dart
  lib/core/ui/schedule/tumble_list_view/tumble_list_view_day_container.dart
  lib/core/ui/schedule/tumble_week_view/tumble_day_of_week_container.dart
  lib/core/ui/schedule/tumble_week_view/tumble_week_event_tile.dart
  lib/core/ui/search/cubit/search_page_cubit.dart
  lib/core/ui/search/cubit/search_page_state.dart
  lib/core/ui/search/search/preview_list_view_day_container.dart
  lib/core/ui/search/search/program_card.dart
  lib/core/ui/search/search/schedule_preview.dart
  lib/core/ui/search/search/tumble_search_page.dart
  lib/locale/app_en.arb
Labels: bug, enhancement

#123 Update vietnamese locale
  lib/locale/app_vi.arb
Labels: locale

#130 Add remaining Chinese translations
  lib/locale/app_de.arb
  lib/locale/app_zh.arb
Labels: locale
