Repository adisve/tumble-for-kronox, pull requests merged in 2022-08, with the labels that each got.

#47 Course colors/force refresh fix
  lib/core/api/repository/cache_and_interaction_repository.dart
  lib/core/extensions/extensions.dart
  lib/core/models/api_models/schedule_model.dart
  lib/core/theme/cubit/theme_state.dart
  lib/core/ui/main_app/cubit/main_app_cubit.dart
  lib/core/ui/schedule/tumble_list_view/tumble_list_view.dart
  lib/core/ui/search/search/tumble_search_page.dart
Labels: bug

#49 Add notification offset setting
  lib/core/api/builders/notification_service_builder.dart
  lib/core/extensions/extensions.dart
  lib/core/ui/main_app/cubit/main_app_cubit.dart
  lib/core/ui/main_app/misc/tumble_app_drawer_tile.dart
  lib/core/ui/main_app/misc/tumble_drawer/cubit/drawer_cubit.dart
  lib/core/ui/main_app/misc/tumble_drawer/cubit/drawer_state.dart
  lib/core/ui/main_app/misc/tumble_drawer/drawer_generic/app_default_schedule_picker.dart
  lib/core/ui/main_app/misc/tumble_drawer/drawer_generic/app_default_view_picker.dart
  lib/core/ui/main_app/misc/tumble_drawer/drawer_generic/app_notification_time_picker.dart
  lib/core/ui/main_app/misc/tumble_drawer/drawer_generic/app_theme_picker.dart
  lib/core/ui/main_app/misc/tumble_drawer/tumble_app_drawer.dart
  lib/core/ui/main_app/misc/tumble_settings_section.dart
  lib/core/ui/schedule/event_options.dart
Labels: enhancement

#50 User account/auto registration
  lib/core/api/apiservices/api_endpoints.dart
  lib/core/api/interface/iuser_service.dart
  lib/core/api/repository/backend_repository.dart
  lib/core/api/repository/user_repository.dart
  lib/core/extensions/api_response_extensions.dart
  lib/core/extensions/extensions.dart
  lib/core/models/api_models/multi_registration_result_model.dart
  lib/core/shared/preference_types.dart
  lib/core/shared/setup.dart
  lib/core/ui/account/authenticated_page.dart
  lib/core/ui/account/misc/auto_signup_option.dart
  lib/core/ui/account/misc/user_account_info_external_link.dart
  lib/core/ui/account/tumble_account_page.dart
  lib/core/ui/account/user_account_info.dart
  lib/core/ui/account/user_event_list/modals/available_user_event_modal.dart
  lib/core/ui/account/user_event_list/modals/registered_passed_user_event_modal.dart
  lib/core/ui/account/user_event_list/modals/upcoming_user_event_modal.dart
  lib/core/ui/account/user_event_list/user_event_list.dart
  lib/core/ui/account/user_event_list/user_event_section.dart
  lib/core/ui/login/cubit/auth_cubit.dart
  lib/core/ui/login/cubit/auth_state.dart
  lib/core/ui/main_app/cubit/main_app_cubit.dart
  lib/core/ui/main_app/misc/tumble_drawer/tumble_app_drawer.dart
  lib/core/ui/schedule/tumble_list_view/data/cupertino_alerts.dart
  lib/core/ui/search/search/program_card.dart
Labels: enhancement

#54 Update gitignore for VS.
  .gitignore
  lib/core/ui/login/login_page_root.dart
  lib/core/ui/main_app/cubit/main_app_cubit.dart
Labels: bug

#55 Add localization support and full english template locale file
  l10n.yaml
  lib/core/api/apiservices/runtime_error_type.dart
  lib/core/api/repository/backend_repository.dart
  lib/core/api/repository/cache_and_interaction_repository.dart
  lib/core/extensions/api_response_extensions.dart
  lib/core/ui/account/misc/auto_signup_option.dart
  lib/core/ui/account/misc/user_account_info_external_link.dart
  lib/core/ui/account/user_account_info.dart
  lib/core/ui/account/user_event_list/user_event_list.dart
  lib/core/ui/account/user_event_list/user_event_register_button.dart
  lib/core/ui/account/user_info.dart
  lib/core/ui/bottom_nav_bar/tumble_navigation_bar.dart
  lib/core/ui/data/groups/authorized_page.dart
  lib/core/ui/data/groups/calendar_view_page.dart
  lib/core/ui/data/groups/event_options.dart
  lib/core/ui/data/groups/general.dart
  lib/core/ui/data/groups/list_view_page.dart
  lib/core/ui/data/groups/login_page.dart
  lib/core/ui/data/groups/pop_up.dart
  lib/core/ui/data/groups/runtime_errors.dart
  lib/core/ui/data/groups/scaffold_message_types.dart
  lib/core/ui/data/groups/search_page.dart
  lib/core/ui/data/groups/settings_page.dart
  lib/core/ui/data/groups/unauthorized_page.dart
  lib/core/ui/data/groups/user_events.dart
  lib/core/ui/data/groups/week_view_page.dart
  lib/core/ui/data/scaffold_message_types.dart
  lib/core/ui/data/string_constant_group.dart
  lib/core/ui/data/string_constants.dart
  lib/core/ui/init_cubit/init_cubit.dart
  lib/core/ui/login/cubit/auth_cubit.dart
  lib/core/ui/login/login_page_root.dart
  lib/core/ui/main_app/cubit/main_app_cubit.dart
  lib/core/ui/main_app/data/labels.dart
  lib/core/ui/main_app/main_app.dart
  lib/core/ui/main_app/main_app_navigation_root.dart
  lib/core/ui/main_app/misc/tumble_drawer/drawer_generic/app_theme_picker.dart
  lib/core/ui/main_app/misc/tumble_drawer/tumble_app_drawer.dart
  lib/core/ui/main_app/school_selection_page.dart
  lib/core/ui/permission_handler.dart
  lib/core/ui/schedule/event_options.dart
  lib/core/ui/schedule/modal_info_row.dart
  lib/core/ui/schedule/tumble_calendar_view/tumble_calendar_view.dart
  lib/core/ui/schedule/tumble_list_view/data/cupertino_alerts.dart
  lib/core/ui/schedule/tumble_list_view/tumble_list_view.dart
  lib/core/ui/schedule/tumble_list_view/tumble_list_view_day_container.dart
  lib/core/ui/schedule/tumble_list_view/tumble_list_view_schedule_card.dart
  lib/core/ui/schedule/tumble_week_view/tumble_day_of_week_container.dart
  lib/core/ui/schedule/tumble_week_view/tumble_day_of_week_divider.dart
  lib/core/ui/schedule/tumble_week_view/tumble_empty_week_event_tile.dart
  lib/core/ui/schedule/tumble_week_view/tumble_week_view.dart
  lib/core/ui/schedule/tumble_week_view/week_number.dart
  lib/core/ui/search/search/schedule_search_bar.dart
  lib/locale/app_en.arb
  lib/locale/app_sv.arb
  pubspec.yaml
Labels: enhancement

#61 Allow login animation to play before page switch
  lib/core/ui/login/cubit/auth_cubit.dart
  lib/core/ui/login/cubit/auth_state.dart
  lib/core/ui/login/login_page_root.dart
  lib/core/ui/main_app/main_app_navigation_root.dart
Labels: enhancement

#62 Add new strings to localized data
  lib/core/ui/data/groups/support_modal.dart
  lib/core/ui/main_app/main_app_navigation_root.dart
  lib/core/ui/main_app/misc/tumble_drawer/support_modal/support_modal.dart
  lib/locale/app_en.arb
Labels: locale
